apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-aas-proxy
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: consumer-aas-proxy
  template:
    metadata:
      labels:
        app: consumer-aas-proxy
    spec:
      containers:
      - image: cxtsiacr.azurecr.io/edc/consumer-aas-proxy:catenax-at-home-latest
        imagePullPolicy: Always
        name: hub-service
        ports:
        - containerPort: 4245 # API
        - containerPort: 8090 # JDB
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-aas-proxy
spec:
  type: ClusterIP
  ports:
  - port: 4245
    targetPort: 4245
  selector:
    app: consumer-aas-proxy
