apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-aas-service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: provider-aas-service
  template:
    metadata:
      labels:
        app: provider-aas-service
    spec:
      containers:
      - image: cxtsiacr.azurecr.io/backend/simple-aas-adapter:catenax-at-home-latest
        imagePullPolicy: Always
        name: provider-aas-service
        ports:
        - containerPort: 4244 # API
        - containerPort: 8090 # JDB